source "https://rubygems.org"

gem "rake", "~> 13.0"
gem "minitest", "~> 5.0"
gem "rubocop", "~> 1.21"
gem "sidekiq", "~> 6.4"
gem "mandate", "~> 1.0"
gem "sinatra", "~> 2.2"
gem "zeitwerk", "~> 2.5"
gem "sinatra-contrib", "~> 2.2"
gem "puma", "~> 5.6"
